package com.taiji.cc.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.taiji.cc.greendao.bean.IpAddress;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IP_ADDRESS".
*/
public class IpAddressDao extends AbstractDao<IpAddress, Long> {

    public static final String TABLENAME = "IP_ADDRESS";

    /**
     * Properties of entity IpAddress.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Ip = new Property(1, String.class, "ip", false, "IP");
        public final static Property Port = new Property(2, int.class, "port", false, "PORT");
        public final static Property ServerName = new Property(3, String.class, "serverName", false, "SERVER_NAME");
    };


    public IpAddressDao(DaoConfig config) {
        super(config);
    }
    
    public IpAddressDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IP_ADDRESS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IP\" TEXT NOT NULL ," + // 1: ip
                "\"PORT\" INTEGER NOT NULL ," + // 2: port
                "\"SERVER_NAME\" TEXT NOT NULL );"); // 3: serverName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IP_ADDRESS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IpAddress entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getIp());
        stmt.bindLong(3, entity.getPort());
        stmt.bindString(4, entity.getServerName());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IpAddress entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getIp());
        stmt.bindLong(3, entity.getPort());
        stmt.bindString(4, entity.getServerName());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public IpAddress readEntity(Cursor cursor, int offset) {
        IpAddress entity = new IpAddress( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // ip
            cursor.getInt(offset + 2), // port
            cursor.getString(offset + 3) // serverName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IpAddress entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIp(cursor.getString(offset + 1));
        entity.setPort(cursor.getInt(offset + 2));
        entity.setServerName(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IpAddress entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IpAddress entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
